-- Supabase Database Schema for TailorApp
-- Migration from Firebase Firestore to Supabase PostgreSQL

-- Create storage bucket for avatars/profile images
INSERT INTO STORAGE.BUCKETS (
    ID,
    NAME,
    PUBLIC
) VALUES (
    'avatars',
    'avatars',
    TRUE
);

-- Users table (main authentication table)
CREATE TABLE USERS (
    ID UUID PRIMARY KEY DEFAULT AUTH.UID(),
    NAME TEXT NOT NULL,
    EMAIL TEXT UNIQUE NOT NULL,
    PHONE TEXT UNIQUE,
    DATE_OF_BIRTH DATE,
    GENDER TEXT,
    PROFILE_IMAGE_URL TEXT,
    ROLE TEXT NOT NULL DEFAULT 'customer' CHECK (ROLE IN ('customer', 'tailor', 'admin')),
    IS_VERIFIED BOOLEAN DEFAULT FALSE,
    IS_ACTIVE BOOLEAN DEFAULT TRUE,
    ADDRESS JSONB,
    CUSTOMER_DATA JSONB,
    TAILOR_DATA JSONB,
    ADMIN_DATA JSONB,
    CREATED_AT TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    UPDATED_AT TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Customers table (for customer-specific data)
CREATE TABLE CUSTOMERS (
    ID UUID PRIMARY KEY DEFAULT GEN_RANDOM_UUID(),
    USER_ID UUID REFERENCES USERS(ID) ON DELETE CASCADE,
    NAME TEXT NOT NULL,
    EMAIL TEXT UNIQUE NOT NULL,
    PHONE TEXT UNIQUE,
    DATE_OF_BIRTH DATE,
    GENDER TEXT,
    PROFILE_IMAGE_URL TEXT,
    MEASUREMENTS JSONB,
    STYLE_PREFERENCES JSONB NOT NULL DEFAULT '{}',
    ADDRESS JSONB,
    IS_VERIFIED BOOLEAN DEFAULT FALSE,
    CREATED_AT TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    UPDATED_AT TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Tailors table
CREATE TABLE TAILORS (
    ID UUID PRIMARY KEY DEFAULT GEN_RANDOM_UUID(),
    USER_ID UUID REFERENCES USERS(ID) ON DELETE CASCADE,
    NAME TEXT NOT NULL,
    EMAIL TEXT UNIQUE NOT NULL,
    PHONE TEXT UNIQUE,
    LOCATION TEXT,
    PROFILE_IMAGE_URL TEXT,
    PROFILE JSONB NOT NULL DEFAULT '{}',
    BUSINESS_INFO JSONB NOT NULL DEFAULT '{}',
    SPECIALIZATIONS TEXT[] DEFAULT '{}',
    CERTIFICATIONS TEXT[] DEFAULT '{}',
    RATINGS JSONB NOT NULL DEFAULT '{"average_rating": 0, "total_reviews": 0}',
    IS_VERIFIED BOOLEAN DEFAULT FALSE,
    IS_ACTIVE BOOLEAN DEFAULT TRUE,
    VERIFIED_AT TIMESTAMP WITH TIME ZONE,
    CREATED_AT TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    UPDATED_AT TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Admins table
CREATE TABLE ADMINS (
    ID UUID PRIMARY KEY DEFAULT GEN_RANDOM_UUID(),
    USER_ID UUID REFERENCES USERS(ID) ON DELETE CASCADE,
    NAME TEXT NOT NULL,
    EMAIL TEXT UNIQUE NOT NULL,
    PHONE TEXT UNIQUE,
    ROLE TEXT NOT NULL DEFAULT 'admin' CHECK (ROLE IN ('admin', 'super_admin')),
    PERMISSIONS TEXT[] DEFAULT '{}',
    PROFILE JSONB NOT NULL DEFAULT '{}',
    PROFILE_IMAGE_URL TEXT,
    IS_ACTIVE BOOLEAN DEFAULT TRUE,
    IS_VERIFIED BOOLEAN DEFAULT FALSE,
    CREATED_AT TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    UPDATED_AT TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Orders table
CREATE TABLE ORDERS (
    ID UUID PRIMARY KEY DEFAULT GEN_RANDOM_UUID(),
    ORDER_NUMBER TEXT UNIQUE NOT NULL,
    CUSTOMER_ID UUID REFERENCES CUSTOMERS(ID) ON DELETE CASCADE,
    TAILOR_ID UUID REFERENCES TAILORS(ID),
    CUSTOMER_NAME TEXT NOT NULL,
    STATUS TEXT NOT NULL DEFAULT 'pending' CHECK (STATUS IN ('pending', 'confirmed', 'in_progress', 'completed', 'cancelled')),
    PAYMENT_STATUS TEXT NOT NULL DEFAULT 'pending' CHECK (PAYMENT_STATUS IN ('pending', 'paid', 'failed', 'refunded')),
    PAYMENT_ID TEXT,
    TOTAL_AMOUNT DECIMAL(10, 2) NOT NULL DEFAULT 0,
    REFUND_AMOUNT DECIMAL(10, 2),
    REFUND_REASON TEXT,
    REFUND_REQUESTED_AT TIMESTAMP WITH TIME ZONE,
    STATUS_MESSAGE TEXT,
    ORDER_DETAILS JSONB NOT NULL DEFAULT '{}',
    DELIVERY_ADDRESS JSONB,
    ESTIMATED_DELIVERY DATE,
    CREATED_AT TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    UPDATED_AT TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Garments table
CREATE TABLE GARMENTS (
    ID UUID PRIMARY KEY DEFAULT GEN_RANDOM_UUID(),
    NAME TEXT NOT NULL,
    TYPE TEXT NOT NULL,
    STATUS TEXT NOT NULL DEFAULT 'draft' CHECK (STATUS IN ('draft', 'active', 'inactive', 'discontinued')),
    CUSTOMER_ID UUID REFERENCES CUSTOMERS(ID),
    PRICE DECIMAL(10, 2) NOT NULL DEFAULT 0,
    DESCRIPTION TEXT,
    SPECIFICATIONS JSONB NOT NULL DEFAULT '{}',
    IMAGES TEXT[] DEFAULT '{}',
    CREATED_AT TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    UPDATED_AT TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Fabrics table (for fabric library)
CREATE TABLE FABRICS (
    ID UUID PRIMARY KEY DEFAULT GEN_RANDOM_UUID(),
    NAME TEXT NOT NULL,
    TYPE TEXT NOT NULL,
    MATERIAL TEXT NOT NULL,
    COLOR TEXT,
    PATTERN TEXT,
    WEIGHT DECIMAL(5, 2),
    PRICE_PER_YARD DECIMAL(10, 2),
    AVAILABILITY_STATUS TEXT DEFAULT 'available' CHECK (AVAILABILITY_STATUS IN ('available', 'out_of_stock', 'discontinued')),
    SUPPLIER TEXT,
    DESCRIPTION TEXT,
    IMAGES TEXT[] DEFAULT '{}',
    PROPERTIES JSONB NOT NULL DEFAULT '{}',
    CREATED_AT TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    UPDATED_AT TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Patterns table (for pattern library)
CREATE TABLE PATTERNS (
    ID UUID PRIMARY KEY DEFAULT GEN_RANDOM_UUID(),
    NAME TEXT NOT NULL,
    CATEGORY TEXT NOT NULL,
    DIFFICULTY_LEVEL TEXT DEFAULT 'beginner' CHECK (DIFFICULTY_LEVEL IN ('beginner', 'intermediate', 'advanced')),
    GARMENT_TYPE TEXT NOT NULL,
    DESCRIPTION TEXT,
    INSTRUCTIONS TEXT,
    PATTERN_FILE_URL TEXT,
    PREVIEW_IMAGES TEXT[] DEFAULT '{}',
    MEASUREMENTS_REQUIRED TEXT[] DEFAULT '{}',
    IS_PUBLIC BOOLEAN DEFAULT TRUE,
    CREATED_BY UUID REFERENCES USERS(ID),
    CREATED_AT TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    UPDATED_AT TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- AI Suggestions table
CREATE TABLE AI_SUGGESTIONS (
    ID UUID PRIMARY KEY DEFAULT GEN_RANDOM_UUID(),
    CUSTOMER_ID UUID REFERENCES CUSTOMERS(ID) ON DELETE CASCADE,
    SUGGESTION_TYPE TEXT NOT NULL CHECK (SUGGESTION_TYPE IN ('style', 'fabric', 'pattern', 'measurement')),
    SUGGESTION_DATA JSONB NOT NULL DEFAULT '{}',
    CONFIDENCE_SCORE DECIMAL(3, 2) DEFAULT 0.0,
    IS_ACCEPTED BOOLEAN DEFAULT FALSE,
    FEEDBACK TEXT,
    CREATED_AT TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    UPDATED_AT TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Measurements table
CREATE TABLE MEASUREMENTS (
    ID UUID PRIMARY KEY DEFAULT GEN_RANDOM_UUID(),
    CUSTOMER_ID UUID REFERENCES CUSTOMERS(ID) ON DELETE CASCADE,
    MEASUREMENT_TYPE TEXT NOT NULL DEFAULT 'body' CHECK (MEASUREMENT_TYPE IN ('body', 'garment')),
    MEASUREMENTS JSONB NOT NULL DEFAULT '{}',
    TAKEN_BY UUID REFERENCES USERS(ID),
    NOTES TEXT,
    IS_CURRENT BOOLEAN DEFAULT TRUE,
    CREATED_AT TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    UPDATED_AT TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Chats table (for customer-tailor communication)
CREATE TABLE CHATS (
    ID UUID PRIMARY KEY DEFAULT GEN_RANDOM_UUID(),
    PARTICIPANTS UUID[] NOT NULL,
    LAST_MESSAGE TEXT,
    LAST_MESSAGE_AT TIMESTAMP WITH TIME ZONE,
    IS_ACTIVE BOOLEAN DEFAULT TRUE,
    CREATED_AT TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    UPDATED_AT TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Chat Messages table
CREATE TABLE CHAT_MESSAGES (
    ID UUID PRIMARY KEY DEFAULT GEN_RANDOM_UUID(),
    CHAT_ID UUID REFERENCES CHATS(ID) ON DELETE CASCADE,
    SENDER_ID UUID REFERENCES USERS(ID) ON DELETE CASCADE,
    CONTENT TEXT NOT NULL,
    MESSAGE_TYPE TEXT DEFAULT 'text' CHECK (MESSAGE_TYPE IN ('text', 'image', 'file', 'system')),
    ATTACHMENTS TEXT[] DEFAULT '{}',
    IS_READ BOOLEAN DEFAULT FALSE,
    CREATED_AT TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Notifications table
CREATE TABLE NOTIFICATIONS (
    ID UUID PRIMARY KEY DEFAULT GEN_RANDOM_UUID(),
    USER_ID UUID REFERENCES USERS(ID) ON DELETE CASCADE,
    TITLE TEXT NOT NULL,
    CONTENT TEXT NOT NULL,
    TYPE TEXT NOT NULL CHECK (TYPE IN ('order', 'payment', 'system', 'promotion', 'reminder')),
    DATA JSONB DEFAULT '{}',
    IS_READ BOOLEAN DEFAULT FALSE,
    IS_SENT BOOLEAN DEFAULT FALSE,
    SENT_AT TIMESTAMP WITH TIME ZONE,
    EXPIRES_AT TIMESTAMP WITH TIME ZONE,
    CREATED_AT TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Admin Activity Logs table
CREATE TABLE ADMIN_ACTIVITY_LOGS (
    ID UUID PRIMARY KEY DEFAULT GEN_RANDOM_UUID(),
    ADMIN_ID UUID REFERENCES ADMINS(ID) ON DELETE CASCADE,
    ACTION TEXT NOT NULL,
    DETAILS JSONB NOT NULL DEFAULT '{}',
    IP_ADDRESS INET,
    USER_AGENT TEXT,
    CREATED_AT TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Create indexes for better performance
CREATE INDEX IDX_USERS_EMAIL ON USERS(EMAIL);

CREATE INDEX IDX_USERS_PHONE ON USERS(PHONE);

CREATE INDEX IDX_USERS_ROLE ON USERS(ROLE);

CREATE INDEX IDX_CUSTOMERS_EMAIL ON CUSTOMERS(EMAIL);

CREATE INDEX IDX_CUSTOMERS_PHONE ON CUSTOMERS(PHONE);

CREATE INDEX IDX_TAILORS_EMAIL ON TAILORS(EMAIL);

CREATE INDEX IDX_TAILORS_LOCATION ON TAILORS(LOCATION);

CREATE INDEX IDX_TAILORS_SPECIALIZATIONS ON TAILORS USING GIN(SPECIALIZATIONS);

CREATE INDEX IDX_ORDERS_CUSTOMER_ID ON ORDERS(CUSTOMER_ID);

CREATE INDEX IDX_ORDERS_TAILOR_ID ON ORDERS(TAILOR_ID);

CREATE INDEX IDX_ORDERS_STATUS ON ORDERS(STATUS);

CREATE INDEX IDX_ORDERS_CREATED_AT ON ORDERS(CREATED_AT DESC);

CREATE INDEX IDX_GARMENTS_CUSTOMER_ID ON GARMENTS(CUSTOMER_ID);

CREATE INDEX IDX_GARMENTS_TYPE ON GARMENTS(TYPE);

CREATE INDEX IDX_GARMENTS_STATUS ON GARMENTS(STATUS);

CREATE INDEX IDX_AI_SUGGESTIONS_CUSTOMER_ID ON AI_SUGGESTIONS(CUSTOMER_ID);

CREATE INDEX IDX_MEASUREMENTS_CUSTOMER_ID ON MEASUREMENTS(CUSTOMER_ID);

CREATE INDEX IDX_CHATS_PARTICIPANTS ON CHATS USING GIN(PARTICIPANTS);

CREATE INDEX IDX_CHAT_MESSAGES_CHAT_ID ON CHAT_MESSAGES(CHAT_ID);

CREATE INDEX IDX_CHAT_MESSAGES_SENDER_ID ON CHAT_MESSAGES(SENDER_ID);

CREATE INDEX IDX_NOTIFICATIONS_USER_ID ON NOTIFICATIONS(USER_ID);

CREATE INDEX IDX_NOTIFICATIONS_IS_READ ON NOTIFICATIONS(IS_READ);

CREATE INDEX IDX_ADMIN_ACTIVITY_LOGS_ADMIN_ID ON ADMIN_ACTIVITY_LOGS(ADMIN_ID);

-- Create updated_at triggers
CREATE OR REPLACE FUNCTION UPDATE_UPDATED_AT_COLUMN(
) RETURNS TRIGGER AS
    $$     BEGIN NEW.UPDATED_AT = NOW();
    RETURN NEW;
END;
$$     LANGUAGE 'plpgsql';
 
-- Apply updated_at triggers to all tables
CREATE TRIGGER UPDATE_USERS_UPDATED_AT BEFORE UPDATE ON USERS FOR EACH ROW EXECUTE

FUNCTION UPDATE_UPDATED_AT_COLUMN(
);
CREATE TRIGGER UPDATE_CUSTOMERS_UPDATED_AT BEFORE UPDATE ON CUSTOMERS FOR EACH ROW EXECUTE

FUNCTION UPDATE_UPDATED_AT_COLUMN(
);
CREATE TRIGGER UPDATE_TAILORS_UPDATED_AT BEFORE UPDATE ON TAILORS FOR EACH ROW EXECUTE

FUNCTION UPDATE_UPDATED_AT_COLUMN(
);
CREATE TRIGGER UPDATE_ADMINS_UPDATED_AT BEFORE UPDATE ON ADMINS FOR EACH ROW EXECUTE

FUNCTION UPDATE_UPDATED_AT_COLUMN(
);
CREATE TRIGGER UPDATE_ORDERS_UPDATED_AT BEFORE UPDATE ON ORDERS FOR EACH ROW EXECUTE

FUNCTION UPDATE_UPDATED_AT_COLUMN(
);
CREATE TRIGGER UPDATE_GARMENTS_UPDATED_AT BEFORE UPDATE ON GARMENTS FOR EACH ROW EXECUTE

FUNCTION UPDATE_UPDATED_AT_COLUMN(
);
CREATE TRIGGER UPDATE_FABRICS_UPDATED_AT BEFORE UPDATE ON FABRICS FOR EACH ROW EXECUTE

FUNCTION UPDATE_UPDATED_AT_COLUMN(
);
CREATE TRIGGER UPDATE_PATTERNS_UPDATED_AT BEFORE UPDATE ON PATTERNS FOR EACH ROW EXECUTE

FUNCTION UPDATE_UPDATED_AT_COLUMN(
);
CREATE TRIGGER UPDATE_AI_SUGGESTIONS_UPDATED_AT BEFORE UPDATE ON AI_SUGGESTIONS FOR EACH ROW EXECUTE

FUNCTION UPDATE_UPDATED_AT_COLUMN(
);
CREATE TRIGGER UPDATE_MEASUREMENTS_UPDATED_AT BEFORE UPDATE ON MEASUREMENTS FOR EACH ROW EXECUTE

FUNCTION UPDATE_UPDATED_AT_COLUMN(
);
CREATE TRIGGER UPDATE_CHATS_UPDATED_AT BEFORE UPDATE ON CHATS FOR EACH ROW EXECUTE

FUNCTION UPDATE_UPDATED_AT_COLUMN(
);