// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCpsmaSXJ8GkKTphlqWTdNaVailzG28GjA',
    appId: '1:168050874940:web:a52d66754a3d5b4c9b8139',
    messagingSenderId: '168050874940',
    projectId: 'tailor-ai-52640',
    authDomain: 'tailor-ai-52640.firebaseapp.com',
    storageBucket: 'tailor-ai-52640.firebasestorage.app',
    measurementId: 'G-X3TLTZ2QF9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB2Ntw7CpFyAVkbzlxTUaGoUJ_qjTxKsJg',
    appId: '1:168050874940:android:a43f7ebace16e0679b8139',
    messagingSenderId: '168050874940',
    projectId: 'tailor-ai-52640',
    storageBucket: 'tailor-ai-52640.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCnVqKrg49Qt1jM8VrHC13WKNI9V4cEsrA',
    appId: '1:168050874940:ios:3299ae806a20be159b8139',
    messagingSenderId: '168050874940',
    projectId: 'tailor-ai-52640',
    storageBucket: 'tailor-ai-52640.firebasestorage.app',
    iosClientId: '168050874940-58kjj9etom3bqranh077blbq9447dcc9.apps.googleusercontent.com',
    iosBundleId: 'com.durgas.basicRequirementsPackage',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCnVqKrg49Qt1jM8VrHC13WKNI9V4cEsrA',
    appId: '1:168050874940:ios:3299ae806a20be159b8139',
    messagingSenderId: '168050874940',
    projectId: 'tailor-ai-52640',
    storageBucket: 'tailor-ai-52640.firebasestorage.app',
    iosClientId: '168050874940-58kjj9etom3bqranh077blbq9447dcc9.apps.googleusercontent.com',
    iosBundleId: 'com.durgas.basicRequirementsPackage',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCpsmaSXJ8GkKTphlqWTdNaVailzG28GjA',
    appId: '1:168050874940:web:065a5a0eebd71c9a9b8139',
    messagingSenderId: '168050874940',
    projectId: 'tailor-ai-52640',
    authDomain: 'tailor-ai-52640.firebaseapp.com',
    storageBucket: 'tailor-ai-52640.firebasestorage.app',
    measurementId: 'G-X8S9WM7YRG',
  );

}